blueprint:
  name: Mobile App iOS/Android Update Location
  description: >-
    Android/iOS Mobile App supports several notification command option
    these blueprints provide any easy way to use these features without complex setup.
  domain: script
  source_url: https://github.com/stboch/homeassistant-blueprints/blob/main/mobile_app_location_update.yaml
  input:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

mode: restart

variables:
## These are used to quickly change a blueprint to support every different notification commands
  message: "request_location_update"

sequence:
  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: '{{ message }}'
