blueprint:
  name: Mobile App Android Notification Command Bluetooth
  description: >-
    Android Mobile App supports several notification command option
    these blueprints provide any easy way to use these features without complex setup.
  domain: script
  source_url: https://github.com/stboch/homeassitant-blueprints/mobile_app_android_dnd.yaml
  input:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app
    command_choice:
      name: Command Choice
      description: Choose which to turn on or off Bluetooth
      selector:
        select:
          options:
            - "turn_on"
            - "turn_off"

mode: restart

variables:
## These are used to quickly change a blueprint to support every different notification commands
  title: !input command_choice
  message: "command_bluetooth"

sequence:
  - alias: "Send notification"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: '{{ title }}'
    message: '{{ message }}'
